#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ANTDIV]
// [ANTDIV]$

// $[BTL_BUTTON]
#define HAL_BTL_BUTTON_ENABLE                (1)

#define BSP_BTL_BUTTON_PIN                   (0U)
#define BSP_BTL_BUTTON_PORT                  (gpioPortA)

// [BTL_BUTTON]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE                 (HAL_CLK_HFCLK_SOURCE_HFRCO)
#define HAL_CLK_PLL_CONFIGURATION            (HAL_CLK_PLL_CONFIGURATION_40MHZ)
#define HAL_CLK_EM01CLK_SOURCE               (HAL_CLK_HFCLK_SOURCE_HFRCODPLL)
#define HAL_CLK_EM23CLK_SOURCE               (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define HAL_CLK_EM4CLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define HAL_CLK_RTCCCLK_SOURCE               (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define HAL_CLK_WDOGCLK_SOURCE               (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define BSP_CLK_HFXO_PRESENT                 (0)
#define BSP_CLK_HFXO_FREQ                    (38400000UL)
#define BSP_CLK_HFXO_INIT                     CMU_HFXOINIT_DEFAULT
#define BSP_CLK_HFXO_CTUNE                   (-1)
#define BSP_CLK_LFXO_PRESENT                 (0)
#define BSP_CLK_LFXO_INIT                     CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_FREQ                    (32768U)
#define BSP_CLK_LFXO_CTUNE                   (0U)
// [CMU]$

// $[COEX]
// [COEX]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[EZRADIOPRO]
// [EZRADIOPRO]$

// $[FEM]
// [FEM]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IADC0]
// [IADC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
// [LED]$

// $[LETIMER0]
// [LETIMER0]$

// $[LFXO]
// [LFXO]$

// $[MODEM]
// [MODEM]$

// $[PA]
// [PA]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[PTI]
// [PTI]$

// $[SERIAL]
#define BSP_SERIAL_APP_PORT                  (HAL_SERIAL_PORT_USART0)
#define BSP_SERIAL_APP_TX_PIN                (5U)
#define BSP_SERIAL_APP_TX_PORT               (gpioPortA)

#define BSP_SERIAL_APP_RX_PIN                (6U)
#define BSP_SERIAL_APP_RX_PORT               (gpioPortA)

#define BSP_SERIAL_APP_CTS_PIN               (3U)
#define BSP_SERIAL_APP_CTS_PORT              (gpioPortA)

#define BSP_SERIAL_APP_RTS_PIN               (4U)
#define BSP_SERIAL_APP_RTS_PORT              (gpioPortA)

#define HAL_SERIAL_APP_BAUD_RATE             (115200UL)
#define HAL_SERIAL_APP_FLOW_CONTROL          (HAL_USART_FLOW_CONTROL_NONE)
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[TIMER2]
// [TIMER2]$

// $[TIMER3]
// [TIMER3]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_CTS_PIN                (3U)
#define PORTIO_USART0_CTS_PORT               (gpioPortA)

#define PORTIO_USART0_RTS_PIN                (4U)
#define PORTIO_USART0_RTS_PORT               (gpioPortA)

#define PORTIO_USART0_RX_PIN                 (6U)
#define PORTIO_USART0_RX_PORT                (gpioPortA)

#define PORTIO_USART0_TX_PIN                 (5U)
#define PORTIO_USART0_TX_PORT                (gpioPortA)

#define HAL_USART0_ENABLE                    (1)

#define BSP_USART0_TX_PIN                    (5U)
#define BSP_USART0_TX_PORT                   (gpioPortA)

#define BSP_USART0_RX_PIN                    (6U)
#define BSP_USART0_RX_PORT                   (gpioPortA)

#define BSP_USART0_CTS_PIN                   (3U)
#define BSP_USART0_CTS_PORT                  (gpioPortA)

#define BSP_USART0_RTS_PIN                   (4U)
#define BSP_USART0_RTS_PORT                  (gpioPortA)

#define HAL_USART0_BAUD_RATE                 (115200UL)
#define HAL_USART0_FLOW_CONTROL              (HAL_USART_FLOW_CONTROL_NONE)
// [USART0]$

// $[USART1]
// [USART1]$

// $[USART2]
// [USART2]$

// $[VCOM]
// [VCOM]$

// $[VUART]
// [VUART]$

// $[WDOG]
// [WDOG]$

#if defined(_SILICON_LABS_MODULE)
#include "sl_module.h"
#endif

#endif /* HAL_CONFIG_H */

